#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)

set -e

CHARD_ROOT="/usr/local/bin/chard"
CHARD_RC="$CHARD_ROOT/.chardrc"
MUSL_GCC="$CHARD_ROOT/usr/bin/gcc -static"
MUSL_GXX="$CHARD_ROOT/usr/bin/g++ -static"
MPFR_CFLAGS="-I$CHARD_ROOT/usr/include"
MPFR_LIBS="$CHARD_ROOT/usr/lib/libmpfr.a $CHARD_ROOT/usr/lib/libgmp.a -lm"
BUILD_DIR="$CHARD_ROOT/var/tmp/build"

echo "[+] Creating Chard group and directories..."

sudo mkdir -p "$CHARD_ROOT"/{etc/portage,usr/portage,usr/bin,usr/lib,var/tmp,var/cache/distfiles,var/cache/packages,dev,tmp}
sudo chown -R 1000:1000 /usr/local/bin/chard

echo "[+] Downloading chard configuration files..."
curl -fsSL https://raw.githubusercontent.com/shadowed1/Chard/main/.chardrc   -o "$CHARD_ROOT/.chardrc"
curl -fsSL https://raw.githubusercontent.com/shadowed1/Chard/main/.chard.env   -o "$CHARD_ROOT/chard.env"
curl -fsSL https://raw.githubusercontent.com/shadowed1/Chard/main/.chard.logic -o "$CHARD_ROOT/chard.logic"
mkdir -p "$CHARD_ROOT/etc/portage/repos.conf"

sed -i '/^# <<< CHARD ENV MARKER <<</,/^# <<< END CHARD ENV MARKER <<</d' /home/chronos/user/.bashrc

if ! grep -Fxq "<<< CHARD ENV MARKER <<<" "/home/chronos/user/.bashrc"; then
    cat >> "/home/chronos/user/.bashrc" <<EOF

# <<< CHARD ENV MARKER <<<
source "$CHARD_RC"
# <<< END CHARD ENV MARKER <<<
EOF
    echo "[+] Chard sourced to ~/.bashrc"
else
    echo "${YELLOW}[!] Chard already sourced in ~/.bashrc"
fi

ARCH=$(uname -m)
case "$ARCH" in
    x86_64)   GENTOO_ARCH="amd64" ;;
    i*86)     GENTOO_ARCH="x86" ;;
    aarch64)  GENTOO_ARCH="arm64" ;;
    armv7l)   GENTOO_ARCH="arm" ;;
    ppc64le)  GENTOO_ARCH="ppc64le" ;;
    *) echo "Unknown architecture: $ARCH"; exit 1 ;;
esac

MAKE_CONF="$CHARD_ROOT/etc/portage/make.conf"
echo "[+] Writing $MAKE_CONF..."
bash -c "cat > '$MAKE_CONF' <<EOF
CHOST='${GENTOO_ARCH}-unknown-linux-gnu'
ARCH='${GENTOO_ARCH}'
ACCEPT_KEYWORDS='~${GENTOO_ARCH}'
ROOT='${CHARD_ROOT}'
CFLAGS='-O2 -pipe'
CXXFLAGS='\${CFLAGS}'
PORTAGE_TMPDIR='\${ROOT}/var/tmp'
DISTDIR='\${ROOT}/var/cache/distfiles'
PKGDIR='\${ROOT}/var/cache/packages'
EOF"

echo "[+] make.conf created with ARCH=${GENTOO_ARCH}"

PORTAGE_DIR="$CHARD_ROOT/usr/portage"
SNAPSHOT_URL="https://gentoo.osuosl.org/snapshots/portage-latest.tar.xz"
TMP_TAR="$CHARD_ROOT/var/tmp/portage-latest.tar.xz"

echo "[+] Downloading Portage tree snapshot..."
curl -L -o "$TMP_TAR" "$SNAPSHOT_URL"

echo "[+] Extracting snapshot into $PORTAGE_DIR..."
mkdir -p "$PORTAGE_DIR"
tar -xJf "$TMP_TAR" -C "$PORTAGE_DIR" --strip-components=1
rm -f "$TMP_TAR"

case "$GENTOO_ARCH" in
    amd64) AUTOBUILD_DIR="current-stage3-amd64-systemd" ;;
    x86)   AUTOBUILD_DIR="current-stage3-x86-systemd" ;;
    arm64) AUTOBUILD_DIR="current-stage3-arm64-systemd" ;;
    *) echo "Unsupported architecture: $GENTOO_ARCH"; exit 1 ;;
esac

BASE="https://gentoo.osuosl.org/releases/$GENTOO_ARCH/autobuilds/$AUTOBUILD_DIR/"
STAGE3_FILE=$(curl -fsSL "$BASE" | tr -d '\r' \
    | grep -o "stage3-$GENTOO_ARCH-systemd-[0-9]\+T[0-9]\+Z\.tar\.xz" \
    | sort | tail -n1)

if [ -z "$STAGE3_FILE" ]; then
    echo "ERROR: Could not determine stage3 tarball filename"
    exit 1
fi

mkdir -p "$BUILD_DIR"

TMP_STAGE3="$CHARD_ROOT/var/tmp/$STAGE3_FILE"
echo "[+] Downloading stage3 tarball..."
curl -L -o "$TMP_STAGE3" "$BASE/$STAGE3_FILE"

echo "[+] Extracting stage3 into $CHARD_ROOT..."
sudo tar -xJf "$TMP_STAGE3" -C "$CHARD_ROOT" --strip-components=1
sudo rm -f "$TMP_STAGE3"
sudo chown -R 1000:1000 /usr/local/bin/chard

PROFILE_BASE="$PORTAGE_DIR/profiles/default/linux/$GENTOO_ARCH"
PROFILE_CANDIDATE=$(find "$PROFILE_BASE" -maxdepth 3 -type d -name "systemd" | sort | tail -n1)
if [ -n "$PROFILE_CANDIDATE" ]; then
    REL_TARGET=$(realpath --relative-to="$CHARD_ROOT/etc/portage" "$PROFILE_CANDIDATE")
     ln -sfn "$REL_TARGET" "$CHARD_ROOT/etc/portage/.profile"
    echo "[+] Profile set to ${PROFILE_CANDIDATE#$PROFILE_BASE/}"
else
    echo "${YELLOW}[!] No systemd profile found under $PROFILE_BASE"
fi

curl -fsSL https://raw.githubusercontent.com/shadowed1/Chard/main/chard -o "$CHARD_ROOT/bin/chard"
chmod +x "$CHARD_ROOT/bin/chard"

echo "[+] Bootstrapping musl toolchain..."
TOOLCHAIN_DIR="$CHARD_ROOT/usr/toolchain"
mkdir -p "$TOOLCHAIN_DIR"

case "$ARCH" in
    x86_64) MUSL_ARCH="x86_64"; TOOLCHAIN_URL="https://musl.cc/x86_64-linux-musl-native.tgz" ;;
    aarch64) MUSL_ARCH="aarch64"; TOOLCHAIN_URL="https://musl.cc/aarch64-linux-musl-native.tgz" ;;
    *) echo "No musl toolchain available for $ARCH"; exit 1 ;;
esac

TOOLCHAIN_TAR="$CHARD_ROOT/var/tmp/$(basename "$TOOLCHAIN_URL")"
curl -L -o "$TOOLCHAIN_TAR" "$TOOLCHAIN_URL"
tar -xzf "$TOOLCHAIN_TAR" -C "$TOOLCHAIN_DIR" --strip-components=1
rm -f "$TOOLCHAIN_TAR"

for bin in gcc g++ ar ld ranlib strip; do
    if [ -f "$TOOLCHAIN_DIR/bin/$MUSL_ARCH-linux-musl-$bin" ]; then
         ln -sf "$TOOLCHAIN_DIR/bin/$MUSL_ARCH-linux-musl-$bin" "$CHARD_ROOT/usr/bin/$bin"
    fi
done

echo "[+] Musl toolchain installed and symlinked into $CHARD_ROOT/usr/bin"

ln -sf /usr/local/bin/chard/usr/toolchain/bin/x86_64-linux-musl-gcc     /usr/local/bin/chard/usr/toolchain/bin/musl-gcc
ln -sf /usr/local/bin/chard/usr/toolchain/bin/x86_64-linux-musl-g++     /usr/local/bin/chard/usr/toolchain/bin/musl-g++
ln -sf /usr/local/bin/chard/usr/toolchain/bin/x86_64-linux-musl-cc      /usr/local/bin/chard/usr/toolchain/bin/cc
ln -sf /usr/local/bin/chard/usr/toolchain/bin/x86_64-linux-musl-c++    /usr/local/bin/chard/usr/toolchain/bin/c++
ln -sf $CHARD_ROOT/usr/toolchain/bin/ar     $CHARD_ROOT/usr/bin/ar
ln -sf $CHARD_ROOT/usr/toolchain/bin/ranlib $CHARD_ROOT/usr/bin/ranlib
# ln -sf "$CHARD_ROOT/usr/lib64/libmpfr.so.6.2.2" "$CHARD_ROOT/usr/lib64/libmpfr.so.6"
# ln -sf "$CHARD_ROOT/usr/lib64/libmpfr.so.6.2.2" "$CHARD_ROOT/usr/lib64/libmpfr.so"

 # ldconfig

export CC="$MUSL_GCC"
export CXX="$MUSL_GXX"
export AR="$CHARD_ROOT/usr/bin/ar"
export RANLIB="$CHARD_ROOT/usr/bin/ranlib"
export PATH="$CHARD_ROOT/usr/bin:$CHARD_ROOT/usr/toolchain/bin:$PATH"

export CFLAGS="-I$CHARD_ROOT/usr/include -O2 -pipe -static -fPIC"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-L$CHARD_ROOT/usr/lib -static"
export AWK=/usr/bin/mawk

echo "[+] Exporting compiler paths"

mkdir -p "$CHARD_ROOT/var/tmp"
echo 'int main(){return 0;}' |  tee "$CHARD_ROOT/var/tmp/test.c" >/dev/null
$MUSL_GCC -o "$CHARD_ROOT/var/tmp/test" "$CHARD_ROOT/var/tmp/test.c"
"$CHARD_ROOT/var/tmp/test" && echo "[+] Musl gcc works!"

echo
echo "Installing GNU Make"
echo

MAKE_VERSION="4.4"
MAKE_TAR="make-$MAKE_VERSION.tar.gz"
MAKE_URL="https://ftp.gnu.org/gnu/make/$MAKE_TAR"

cd "$BUILD_DIR"
curl -L -o "$MAKE_TAR" "$MAKE_URL"
tar -xf "$MAKE_TAR"
cd "make-$MAKE_VERSION"

MAKE_CFLAGS="-O2 -pipe"
MAKE_LDFLAGS=""

env PATH="$PATH" CFLAGS="$MAKE_CFLAGS" LDFLAGS="$MAKE_LDFLAGS" ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --disable-dependency-tracking

make -j"$(nproc)"
make install
echo "[+] Make $MAKE_VERSION installed"


echo
echo "Installing GNU GMP"
echo

GMP_VERSION="6.3.0"
GMP_TAR="gmp-$GMP_VERSION.tar.xz"
GMP_URL="https://gmplib.org/download/gmp/$GMP_TAR"

cd "$BUILD_DIR"
curl -L -o "$GMP_TAR" "$GMP_URL"
tar -xf "$GMP_TAR"
cd "gmp-$GMP_VERSION"

 env PATH="$PATH" AWK="$AWK" CC="$MUSL_GCC" CXX="$MUSL_GXX" AR="$AR" RANLIB="$RANLIB" \
    ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --enable-static \
    --disable-shared \
    --with-pic

make -j"$(nproc)"
make install
echo "[+] GMP $GMP_VERSION installed"

echo
echo "Installing MPFR"
echo

MPFR_VERSION="4.2.2"
MPFR_TAR="mpfr-$MPFR_VERSION.tar.xz"
MPFR_URL="https://www.mpfr.org/mpfr-current/$MPFR_TAR"

cd "$BUILD_DIR"
curl -L -o "$MPFR_TAR" "$MPFR_URL"
tar -xf "$MPFR_TAR"
cd "mpfr-$MPFR_VERSION"

env PATH="$PATH" ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --with-gmp="$CHARD_ROOT/usr" \
    --enable-static \
    --disable-shared \
    --with-pic
make -j"$(nproc)"
make install
echo "[+] MPFR $MPFR_VERSION installed"

echo
echo "Installing GAWK"
echo

GAWK_VERSION="5.3.2"
GAWK_TAR="gawk-$GAWK_VERSION.tar.xz"
GAWK_URL="https://ftp.gnu.org/gnu/gawk/$GAWK_TAR"

cd "$BUILD_DIR"
curl -L -o "$GAWK_TAR" "$GAWK_URL"
tar -xf "$GAWK_TAR"
cd "gawk-$GAWK_VERSION"

MPFR_LIBS="$CHARD_ROOT/usr/lib/libmpfr.a $CHARD_ROOT/usr/lib/libgmp.a -lm"
MPFR_CFLAGS="-I$CHARD_ROOT/usr/include"

env PATH="$PATH" ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --disable-shared \
    --enable-static \
    --without-readline \
    --disable-dependency-tracking \
    MPFR_CFLAGS="$MPFR_CFLAGS" \
    MPFR_LIBS="$MPFR_LIBS" \
    CC="$CHARD_ROOT/usr/toolchain/bin/musl-gcc" \
    CXX="$CHARD_ROOT/usr/toolchain/bin/musl-g++" \
    CFLAGS="-I$CHARD_ROOT/usr/include -O2 -pipe -static" \
    CXXFLAGS="-I$CHARD_ROOT/usr/include -O2 -pipe -static" \
    LDFLAGS="-L$CHARD_ROOT/usr/lib -static"

make -j"$(nproc)"
make install
echo "[+] Gawk $GAWK_VERSION installed (fully static)"

echo
echo "Installing BINUTILS"
echo

BINUTILS_VERSION="2.45"
BINUTILS_TAR="binutils-$BINUTILS_VERSION.tar.xz"
BINUTILS_URL="https://ftp.gnu.org/gnu/binutils/$BINUTILS_TAR"

cd "$BUILD_DIR"
curl -L -o "$BINUTILS_TAR" "$BINUTILS_URL"
tar -xf "$BINUTILS_TAR"
cd "binutils-$BINUTILS_VERSION"

env PATH="$PATH" ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --disable-nls \
    --disable-werror \
    --enable-static \
    --disable-shared \
    MPFR_CFLAGS="$MPFR_CFLAGS" \
    MPFR_LIBS="$MPFR_LIBS"

make -j"$(nproc)"
make install
echo "[+] Binutils $BINUTILS_VERSION installed"

echo
echo "Installing Diffutils"
echo

DIFFUTILS_VERSION="3.12"
DIFFUTILS_TAR="diffutils-$DIFFUTILS_VERSION.tar.xz"
DIFFUTILS_URL="https://ftp.gnu.org/gnu/diffutils/$DIFFUTILS_TAR"

cd "$BUILD_DIR"
curl -L -o "$DIFFUTILS_TAR" "$DIFFUTILS_URL"
tar -xf "$DIFFUTILS_TAR"
cd "diffutils-$DIFFUTILS_VERSION"

env PATH="$PATH" ./configure \
    --prefix="$CHARD_ROOT/usr" \
    --disable-dependency-tracking

make -j"$(nproc)"
make install
echo "[+] Diffutils $DIFFUTILS_VERSION installed"

rm -rf "$BUILD_DIR"
echo "[+] All packages built and installed into $CHARD_ROOT/usr/bin"


CHROME_PYTHON=/usr/bin/python3
echo "[+] Bootstrapping Git using ChromeOS Python ($CHROME_PYTHON)..."

echo
echo "Installing Git"
echo

GIT_VERSION="2.51.0"
GIT_TAR="git-$GIT_VERSION.tar.gz"
GIT_URL="https://mirrors.edge.kernel.org/pub/software/scm/git/$GIT_TAR"

cd "$BUILD_DIR"
curl -L -o "$GIT_TAR" "$GIT_URL"
tar -xzf "$GIT_TAR"
cd "git-$GIT_VERSION"

./configure CC="$MUSL_GCC" CXX="$MUSL_GXX" --prefix="$CHARD_ROOT/usr"
make -j"$(nproc)"
make install

cd "$CHARD_ROOT"
rm -rf "$BUILD_DIR"

echo "[+] Git $GIT_VERSION installed into $CHARD_ROOT/usr/bin"
echo
echo "[+] Chard root setup complete."
