#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)

curl -L https://raw.githubusercontent.com/shadowed1/Chard/refs/heads/main/Chard_Installer.sh -o ~/Chard_Installer
echo ""
echo "${GREEN}Downloading to: ~/Chard_Installer"
echo ""
echo "${YELLOW}Run the installer with ${BOLD}${YELLOW}VT-2 or enable sudo in crosh${RESET}${YELLOW}."
echo "Run commands below with sudo in crosh or VT-2:${RESET}"
echo ""
echo ""
echo "${RESET}${GREEN}If on ChromeOS/FydeOS, run the following: ${RESET}"
echo "${RED}${BOLD}sudo mv ~/Chard_Installer /usr/local/Chard_Installer"
echo "sudo bash /usr/local/Chard_Installer${RESET}"
echo ""
echo ""
echo "${GREEN}If on anything else run: ${RESET}"
echo "${CYAN}sudo bash ~/Chard_Installer
